I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/definer.rpy", line 105, in script
    define player = DynamicCharacter(pname,
  File "game/definer.rpy", line 105, in <module>
    define player = DynamicCharacter(pname,
NameError: name 'pname' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/definer.rpy", line 105, in script
    define player = DynamicCharacter(pname,
  File "D:\MY DATA\ren'py\renpy-7.1.3-sdk\renpy\ast.py", line 1979, in execute
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "D:\MY DATA\ren'py\renpy-7.1.3-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/definer.rpy", line 105, in <module>
    define player = DynamicCharacter(pname,
NameError: name 'pname' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
 
Tue Dec 25 21:31:50 2018
